Fix checking availability of mposx_preparebuild command, try to build ffmpeg with llvm.
git-svn-id: svn://mplayerosx.ch/mplayerosx/trunk@115 6577e75b-6453-0410-a6fa-8f9c828ad7c1

diff --git a/Scripts/ffmpeg/build b/Scripts/ffmpeg/build
--- a/Scripts/ffmpeg/build
+++ b/Scripts/ffmpeg/build
@@ -156,7 +156,7 @@ if [[ $no_steps > 1 && $only_steps > 1 ]]; then
 fi
 
 # Check for mposx_preparebuild
-which mposx_preparebuild || echo "ERROR: mposx_preparebuild not found."; exit 1
+which mposx_preparebuild > /dev/null || (echo "ERROR: mposx_preparebuild not found."; exit 1)
 
 # Apply --STEP-only options
 if [[ $clean_only == 1 ]]; then
@@ -205,6 +205,9 @@ config_opts="$config_opts --disable-devices --disable-encoders --disable-muxers 
 config_opts="$config_opts --enable-postproc"
 # Enable runtime cpu detection
 config_opts="$config_opts --enable-runtime-cpudetect"
+# Enable LLCM
+config_opts="$config_opts --cc=llvm-gcc"
+
 
 # PPC platform options
 if [ "$target_system" = "ppc" -o "$target_system" = "ppcg3" ]; then
diff --git a/Scripts/mplayer/build b/Scripts/mplayer/build
--- a/Scripts/mplayer/build
+++ b/Scripts/mplayer/build
@@ -159,7 +159,7 @@ if [[ $no_steps > 1 && $only_steps > 1 ]]; then
 fi
 
 # Check for mposx_preparebuild
-which mposx_preparebuild || echo "ERROR: mposx_preparebuild not found."; exit 1
+which mposx_preparebuild > /dev/null || (echo "ERROR: mposx_preparebuild not found."; exit 1)
 
 # Apply --STEP-only options
 if [[ $clean_only == 1 ]]; then
